WebSiteBanSach/WebSiteBanSach/Controllers/QuanLyChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace WebSiteBanSach.Controllers
{
    public class QuanLyChuDeController : Controller
    {
        //
        // GET: /QuanLyChuDe/
        db1ce907233a3c4e8bb553a55200989dc5Entities db = new db1ce907233a3c4e8bb553a55200989dc5Entities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.ChuDes.ToList().OrderBy(n => n.MaChuDe).ToPagedList(pageNumber, pageSize));
        }
        //Thêm mới 
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(ChuDe cd, HttpPostedFileBase fileUpload)
        {
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                db.ChuDes.Add(cd);
                db.SaveChanges();
            }
            return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaChuDe)
        {
            //Lấy ra đối tượng sách theo mã 
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(cd);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(ChuDe cd, FormCollection f)
        {
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhận trong model
                db.Entry(cd).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");

        }
        //Hiển thị sản phẩm
        public ActionResult HienThi(int MaChuDe)
        {

            //Lấy ra đối tượng sách theo mã 
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(cd);

        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaChuDe)
        {
            //Lấy ra đối tượng sách theo mã 
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(cd);
        }
        [HttpPost, ActionName("Xoa")]

        public ActionResult XacNhanXoa(int MaChuDe)
        {
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            //cd.Saches = null;
            cd.TenChuDe = null;

            db.Entry(cd).State = System.Data.Entity.EntityState.Modified;
            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Infrastructure.DbUpdateException ex)
            {
                Response.Status = ex.InnerException.Message;
                return null;
            }
            return RedirectToAction("Index");

        }
	}
}

WebSiteBanSach/WebSiteBanSach/Views/QuanLyChuDe/ChinhSua.cshtml
@model WebSiteBanSach.Models.ChuDe

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>ChinhSua</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChuDe</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MaChuDe)

        <div class="form-group">
            @Html.LabelFor(model => model.TenChuDe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChuDe)
                @Html.ValidationMessageFor(model => model.TenChuDe)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyChuDe/HienThi.cshtml
@model WebSiteBanSach.Models.ChuDe

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>HienThi</h2>

<div>
    <h4>Thông tin chủ đề</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenChuDe)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaChuDe = Model.MaChuDe }) |
    @Html.ActionLink("Trở về", "Index")
</p>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyChuDe/Index.cshtml
@model IEnumerable<WebSiteBanSach.Models.ChuDe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenChuDe)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenChuDe)
        </td>
        <td>
            @Html.ActionLink("Edit", "ChinhSua", new { @MaChuDe = item.MaChuDe }) |
            @Html.ActionLink("Details", "HienThi", new { @MaChuDe = item.MaChuDe }) |
            @Html.ActionLink("Delete", "Xoa", new { @MaChuDe = item.MaChuDe })
        </td>
    </tr>
}

</table>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyChuDe/ThemMoi.cshtml
@model WebSiteBanSach.Models.ChuDe

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>ThemMoi</h2>
@*Thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("ThemMoi", "QuanLyChuDe", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chủ đề</h4>
        <hr />
        @Html.ValidationSummary(true)



        <div class="form-group">
            @Html.LabelFor(model => model.TenChuDe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChuDe)
                @Html.ValidationMessageFor(model => model.TenChuDe)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyChuDe/Xoa.cshtml
@model WebSiteBanSach.Models.ChuDe

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Xoa</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChuDe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenChuDe)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>