WebSiteBanSach/WebSiteBanSach/Controllers/QuanLyTaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace WebSiteBanSach.Controllers
{
    public class QuanLyTaiKhoanController : Controller
    {
        //
        // GET: /QuanLySanPham/
        db1ce907233a3c4e8bb553a55200989dc5Entities db = new db1ce907233a3c4e8bb553a55200989dc5Entities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.KhachHangs.ToList().OrderBy(n => n.MaKH).ToPagedList(pageNumber, pageSize));
        }
        //Thêm mới 
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(KhachHang kh, HttpPostedFileBase fileUpload)
        {
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                db.KhachHangs.Add(kh);
                db.SaveChanges();
            }
            return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaKH)
        {
            //Lấy ra đối tượng sách theo mã 
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == MaKH);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(KhachHang kh, FormCollection f)
        {
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhận trong model
                db.Entry(kh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //Hiển thị sản phẩm
        public ActionResult HienThi(int MaKH)
        {
            //Lấy ra đối tượng sách theo mã 
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == MaKH);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(kh);
        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaKH)
        {
            //Lấy ra đối tượng sách theo mã 
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == MaKH);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(kh);
        }
        [HttpPost, ActionName("Xoa")]

        public ActionResult XacNhanXoa(int MaKH)
        {
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.MaKH == MaKH);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            kh.DiaChi = null;
            kh.DienThoai = null;
            kh.Email = null;
            kh.GioiTinh = null;
            kh.HoTen = null;
            kh.NgaySinh = null;
            kh.MatKhau = null;
            kh.TaiKhoan = null;
          
            db.Entry(kh).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        //Chỉnh sửa thông tin tài khoản
        public ActionResult AdminProfile()
        {
            //Lấy ra đối tượng sách theo mã 
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == "admin");
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);

        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AdminProfile(KhachHang kh, FormCollection f)
        {
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhận trong model
                db.Entry(kh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }


            return RedirectToAction("AdminProfile");
        }
    }
}

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/AdminProfile.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "ThongTinKhachHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h2>Chỉnh sửa thông tin khách hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Khách Hàng</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaKH</span>
                @Html.Hidden("MaKH", Model.MaKH)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen)
                @Html.ValidationMessageFor(model => model.HoTen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh)
                @Html.ValidationMessageFor(model => model.NgaySinh)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GioiTinh)
                @Html.ValidationMessageFor(model => model.GioiTinh)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai)
                @Html.ValidationMessageFor(model => model.DienThoai)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan)
                @Html.ValidationMessageFor(model => model.TaiKhoan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau)
                @Html.ValidationMessageFor(model => model.MatKhau)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>


    </div>
}

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/ChinhSua.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Chỉnh sửa thông tin khách hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Khách Hàng</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaKH</span>
                @Html.Hidden("MaKH", Model.MaKH)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen)
                @Html.ValidationMessageFor(model => model.HoTen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh)
                @Html.ValidationMessageFor(model => model.NgaySinh)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GioiTinh)
                @Html.ValidationMessageFor(model => model.GioiTinh)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai)
                @Html.ValidationMessageFor(model => model.DienThoai)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan)
                @Html.ValidationMessageFor(model => model.TaiKhoan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau)
                @Html.ValidationMessageFor(model => model.MatKhau)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>


    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/HienThi.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>HienThi</h2>

<div>
    <h4>Thông tin khách hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaKH = Model.MaKH }) |
    @Html.ActionLink("Trở về", "Index")
</p>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<WebSiteBanSach.Models.KhachHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Thêm mới khách hàng", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().HoTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgaySinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TaiKhoan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MatKhau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaKH = item.MaKH }) |
                @Html.ActionLink("Hiển thị", "HienThi", new { @MaKH = item.MaKH }) |
                @Html.ActionLink("Xoa", "Xoa", new { @MaKH = item.MaKH })
            </td>
        </tr>
    }

</table>
@* Tạo link liên kết các trang*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/ThemMoi.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>ThemMoi</h2>
@*Thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("ThemMoi", "QuanLyTaiKhoan", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Khách hàng</h4>
        <hr />
        @Html.ValidationSummary(true)



        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen)
                @Html.ValidationMessageFor(model => model.HoTen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh)
                @Html.ValidationMessageFor(model => model.NgaySinh)
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh)
                @Html.ValidationMessageFor(model => model.GioiTinh)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai)
                @Html.ValidationMessageFor(model => model.DienThoai)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan)
                @Html.ValidationMessageFor(model => model.TaiKhoan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau)
                @Html.ValidationMessageFor(model => model.MatKhau)
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi)
                @Html.ValidationMessageFor(model => model.DiaChi)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebSiteBanSach/WebSiteBanSach/Views/QuanLyTaiKhoan/Xoa.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h3>Bạn có thật sự muốn xóa khách hàng này?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }
</div>