WebSiteBanSach/WebSiteBanSach/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
using PagedList.Mvc;

namespace WebSiteBanSach.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        db1ce907233a3c4e8bb553a55200989dc5Entities db = new db1ce907233a3c4e8bb553a55200989dc5Entities();
        public ActionResult Index(int? page)
        {
            //Tạo biến số sản phẩm trên trang
            int pageSize = 9;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(db.Saches.Where(n => n.Moi == 1).OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }

    }
}

WebSiteBanSach/WebSiteBanSach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;

namespace WebSiteBanSach.Controllers
{
    public class SachController : Controller
    {
        //
        // GET: /SachMoiPartial/
        db1ce907233a3c4e8bb553a55200989dc5Entities db = new db1ce907233a3c4e8bb553a55200989dc5Entities();
        public PartialViewResult SachMoiPartial()
        {
            var lstSachMoi = db.Saches.Take(3).ToList();
            return PartialView(lstSachMoi);
        }
        //Xem chi tiết
        public ViewResult XemChiTiet(int MaSach=0)
        {
            Sach sach = db.Saches.SingleOrDefault(n=>n.MaSach==MaSach);
            if (sach == null)
            { 
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            //ChuDe cd = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe);
            //ViewBag.TenCD = cd.TenChuDe;
            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;
            return View(sach);
        }
	}
}

WebSiteBanSach/WebSiteBanSach/Views/Home/Index.cshtml
@using WebSiteBanSach.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<Sach>

@*Css cho trang chủ ở trong thư mục content*@
<link href="~/Content/TrangChuCss.css" rel="stylesheet" />
@{
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
    ViewBag.Title = "Index";
}
@section NoiDungBenPhai{
    <div>
        aaa
    </div>
}
@*divBody trang index*@
<h2 style="margin-left:2%;font-weight:normal;color:black">Sách mới xuất bản</h2>
<hr />
@*
    Chú thích:
    -Div divBody chứa Div SanPham
    -Div SanPham chứa Div AnhBia,ThongTin
    -Div ThongTin chứa Div TenSach,DonGia
*@

<div id="divBody" style="background:White;">
    @{int i = 0;}
    @foreach (var item in Model)
    {
        i++;
        <div id="SanPham">
            <a href="@Url.Action("XemChiTiet", "Sach", new { @MaSach=item.MaSach })">  <div id="AnhBia"><img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="100" height="150" /></div></a>
            <div id="ThongTin">
                @*Nếu tên sách dài hơn 30 ký tự thì chúng ta sẽ cắt tên sách ra lấy từ ký tự 0 đến ký tự 35*@
                @if (item.TenSach.Length < 35)
                {
                    <div id="TenSach" title="@item.TenSach">@item.TenSach.</div>
                }
                else
                {
                    <div id="TenSach" title="@item.TenSach"> @item.TenSach.Substring(0, 35) ...</div>
                }
                @*Dịch dấu chấm động đơn giá sử dụng string.Format("{0:0,0}", tham số)*@
                <div id="DonGia" style="color:orange"><font color="Green">Giá:</font> @String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
            </div>
            <div id="GioHang">
                @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMaSach = item.MaSach, @strURL = Request.Url.ToString() }))
                {
                    <input type="submit" style="cursor:pointer" value="Mua hàng &#xf07a;" id="btnGioHang" class="btn btn-primary">
                }
            </div>
        </div>
        if (i % 3 == 0)
        {
            <div style="clear:both"></div>
        }
    }

</div>
<div style="clear:both"></div>
@* Tạo link liên kết các trang*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>