WebSiteBanSach/WebSiteBanSach/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace WebSiteBanSach.Controllers
{
    public class NguoiDungController : Controller
    {
        static public KhachHang kh = null;
        private ICustomerRepository repository = null;
        db1ce907233a3c4e8bb553a55200989dc5Entities db = new db1ce907233a3c4e8bb553a55200989dc5Entities();
 
          public NguoiDungController() 
          { 
            this.repository = new CustomerRepository(); 
          }

          public NguoiDungController(ICustomerRepository repository) 
          { 
            this.repository = repository;
          } 
         
          public ActionResult Index() 
          { 
            //List model = (List)repository.SelectAll(); 
            return View(); 
          } 
         
          public ActionResult New() 
          { 
            return View(); 
          } 
         
          public ActionResult Insert(KhachHang obj) 
          { 
            repository.Insert(obj); 
            repository.Save(); 
            return View(); 
          } 
         
          public ActionResult Edit(string id) 
          { 
            KhachHang existing = repository.SelectByID(id); 
            return View(existing); 
          } 
         
          public ActionResult Update(KhachHang obj) 
          { 
            repository.Update(obj); 
            repository.Save(); 
            return View(); 
          } 
         
          public ActionResult ConfirmDelete(string id) 
          { 
            KhachHang existing = repository.SelectByID(id); 
            return View(existing); 
          } 
         
          public ActionResult Delete(string id) 
          { 
            repository.Delete(id); 
            repository.Save(); 
            return View(); 
          }


        //QuanLyBanSachEntities db = new QuanLyBanSachEntities();


        //// GET: /NguoiDung/
        //public ActionResult Index()
        //{
        //    return View();
        //}
        [HttpGet]
        public ActionResult DangKy()
        {

            return View();
        }
        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult DangKy(KhachHang kh, FormCollection f)
        {
            
            string sHoTen = f["txtHoTen"].ToString();
            string sNgaySinh = f["txtNgaySinh"].ToString();
            string sGioiTinh = f["txtGioiTinh"].ToString();
            string sDienThoai = f["txtDienThoai"].ToString();
            string sEmail = f["txtEmail"].ToString();
            string sDiaChi = f["txtDiaChi"].ToString();
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau1 = f.Get("txtMatKhau1").ToString();
            string sMatKhau2 = f.Get("txtMatKhau2").ToString();

            ViewBag.ThongBao = "";

            if (sHoTen == "")
            {
                ViewBag.ThongBao = "Họ tên không được để trống!";
                return View();
            }
            if (sNgaySinh == "")
            {
                ViewBag.ThongBao = "Ngày sinh không được để trống!";
                return View();
            }
            if (sGioiTinh == "")
            {
                ViewBag.ThongBao = "Giới tính không được để trống!";
                return View();
            }
            if (sDienThoai == "")
            {
                ViewBag.ThongBao = "Điện thoại không được để trống!";
                return View();
            }
            if (sEmail == "")
            {
                ViewBag.ThongBao = "Email không được để trống!";
                return View();
            }
            if (sDiaChi == "")
            {
                ViewBag.ThongBao = "Địa chỉ không được để trống!";
                return View();
            }
            if (sTaiKhoan == "")
            {
                ViewBag.ThongBao = "Tài khoản không được để trống!";
                return View();
            }
            else
            {
                KhachHang temp = null;
                temp = db.KhachHangs.FirstOrDefault(n => n.TaiKhoan == sTaiKhoan);
                if (temp != null)
                    ViewBag.ThongBao = "Tài khoản đã có người đăng ký";
            }
            if (sMatKhau1 == "" || sMatKhau2 == "")
            {
                ViewBag.ThongBao = "Mật khẩu không được để trống!";
                return View();
            }
            if (sMatKhau1 != sMatKhau2)
            {
                ViewBag.ThongBao = "Mật khẩu không trùng khớp!";
                return View();
            }

            

            if (ViewBag.ThongBao == "")
            {
                ViewBag.ThongBao = "Đăng ký thành công!";
                //KhachHang kh = new KhachHang();
                kh.HoTen = sHoTen;
                kh.GioiTinh = sGioiTinh;
                kh.MatKhau = sMatKhau1;
                kh.NgaySinh = Convert.ToDateTime(sNgaySinh);
                kh.TaiKhoan = sTaiKhoan;
                kh.DienThoai = sDienThoai;
                kh.DiaChi = sDiaChi;
                kh.Email = sEmail;

                if (ModelState.IsValid)
                {
                    db.KhachHangs.Add(kh);
                    db.SaveChanges();
                }
                return View();
            }
            return View();
            
            /*
            ViewBag.ThongBao = "";

            if (kh.HoTen == "")
            {
                ViewBag.ThongBao = "Họ tên không được để trống!";
                return View();
            }

            string sNgaySinh = f["txtNgaySinh"].ToString();

            if (sNgaySinh == "")
            {
                ViewBag.ThongBao = "Ngày sinh không được để trống!";
                return View();
            }
            else
                kh.NgaySinh = Convert.ToDateTime(sNgaySinh);

            if (kh.GioiTinh == "")
            {
                ViewBag.ThongBao = "Giới tính không được để trống!";
                return View();
            }
            if (kh.DienThoai == "")
            {
                ViewBag.ThongBao = "Điện thoại không được để trống!";
                return View();
            }
            if (kh.Email == "")
            {
                ViewBag.ThongBao = "Email không được để trống!";
                return View();
            }
            if (kh.DiaChi == "")
            {
                ViewBag.ThongBao = "Địa chỉ không được để trống!";
                return View();
            }
            if (kh.TaiKhoan == "")
            {
                ViewBag.ThongBao = "Tài khoản không được để trống!";
                return View();
            }
            else
            {
                KhachHang temp = null;
                temp = db.KhachHangs.FirstOrDefault(n => n.TaiKhoan == kh.TaiKhoan);
                if (temp != null)
                    ViewBag.ThongBao = "Tài khoản đã có người đăng ký";
            }
            string sMatKhau2 = f.Get("txtMatKhau2").ToString();

            if (kh.MatKhau == "" || sMatKhau2 == "")
            {
                ViewBag.ThongBao = "Mật khẩu không được để trống!";
                return View();
            }
            if (kh.MatKhau != sMatKhau2)
            {
                ViewBag.ThongBao = "Mật khẩu không trùng khớp!";
                return View();
            }

            repository.Insert(kh);
            repository.Save();
            return View();*/
        }
        [HttpGet]
        public ActionResult DangNhap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f.Get("txtMatKhau").ToString();
            List<KhachHang> listkh = (List<KhachHang>)repository.SelectAll();
            
            foreach (var item in listkh)
            {
                if (sTaiKhoan == item.TaiKhoan && sMatKhau == item.MatKhau)
                    kh = item;
            }

            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng bạn đăng nhập thành công !";
                Session["TaiKhoan"] = kh;
                if(kh.TaiKhoan == "admin")
                {
                    return RedirectToAction("Index","QuanLySanPham");
                }
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng!";
            return View();
        }
        //tạo partial đăng nhập
        public ActionResult DangNhapPartial()
        {
            if(kh == null)
                ViewBag.TenTaiKhoan = "Đăng Nhập";
            else
                ViewBag.TenTaiKhoan = kh.TaiKhoan;
            return PartialView();
        }

        //tạo partial đăng nhập
        public ActionResult DangKyPartial()
        {
            if (kh == null)
                ViewBag.TenTaiKhoan = "Đăng Ký";

            return PartialView();
        }

        public ActionResult Logout()
        {
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            kh = null;
            Session.Clear();

            return RedirectToAction("Index", "Home");

        }

        //Chỉnh sửa thông tin tài khoản
        public ActionResult ThongTinKhachHang()
        {
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //tải lại thông tin khách hàng
            List<KhachHang> listkh = (List<KhachHang>)repository.SelectAll();
            KhachHang temp = kh;
            foreach (var item in listkh)
            {
                if (kh.MaKH == item.MaKH)
                    temp = item;
            }
            return View(temp);
            
        }
        [HttpPost]

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/ChinhSua.cshtml
@using WebSiteBanSach.Models
@model List<ChiTietDonHang>

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>Chỉnh sửa thông tin chi tiết đơn hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Đơn Hàng</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(modelitem => Model.First().MaDonHang, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.First().MaDonHang</span>
                @Html.Hidden("MaDonHang", Model.First().MaDonHang)
            </div>
        </div>
        <br />
@foreach (var item in Model)
{
        <div class="form-group">
            @Html.LabelFor(modelitem => item.Sach.TenSach, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@item.Sach.TenSach</span>
                @Html.Hidden("MaDonHang", item.Sach.TenSach)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(modelitem => item.SoLuong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => item.SoLuong)
                @Html.ValidationMessageFor(model => item.SoLuong)
            </div>
        </div>
}
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "LichSuMuaHang")
</div>

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/DangKy.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}
<h2>
    Đăng ký
</h2>
<h1>@ViewBag.ThongBao</h1>
<div style="padding-left:100px;">
    @using (Html.BeginForm())
    {
        @*@Html.AntiForgeryToken()*@
        
        <div class="form-horizontal">
            <h4>Đăng ký</h4>
            <hr />
            @Html.ValidationSummary(false)
            
            
            
  
        <span>Họ tên :</span>
        <br />
        <input name="txtHoTen" type="text" />
        <br />
        <span>Ngày sinh :</span>
        <br />
        <input name="txtNgaySinh" type="date" />
        <br />
        <span>Giới tính :</span>
        <br />
        <input name="txtGioiTinh" type="text" />
        <br />
        <span>Điện thoại :</span>
        <br />
        <input name="txtDienThoai" type="text" />
        <br />
        
        <span>Tài khoản :</span>
        <br />
        @Html.TextBox("txtTaiKhoan");
        <br />
        <span>Mật khẩu:</span>
        <br />
        <input name="txtMatKhau1" type="password" />
        <br />
        <span>Nhập lại mật khẩu:</span>
        <br />
        <input name="txtMatKhau2" type="password" />
        <br />
        
        <span>Email :</span>
        <br />
        <input name="txtEmail" type="text" />
        <br />
        <span>Địa chỉ :</span>
        <br />
        <input name="txtDiaChi" type="text" />
        <br />
        
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="btnSubmit" type="submit" value="Đăng ký" class="btn btn-group-vertical" />
                </div>
            </div>
        </div>

    }
</div>

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/DangKyPartial.cshtml
@{if (@ViewBag.TenTaiKhoan == "Đăng Ký")
{<a href="@Url.Action("DangKy","NguoiDung")"> @ViewBag.TenTaiKhoan</a>}
else
{
    <a href="@Url.Action("Logout","NguoiDung")"> Logout </a> }
} 

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>
    Đăng nhập
</h2>
<h1>@ViewBag.ThongBao</h1>
@using (Html.BeginForm())
{   <span>Tài khoản :</span> <br />
    @Html.TextBox("txtTaiKhoan");
    <br />
    <span>Mật khẩu:</span><br />
    <input name="txtMatKhau" type="password" />
    <br />
    <input type="submit" id="btnSubmit" name="btnSubmit" />

}

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/DangNhapPartial.cshtml
@{if(@ViewBag.TenTaiKhoan == "Đăng Nhập")
  {<a href="@Url.Action("DangNhap","NguoiDung")"> @ViewBag.TenTaiKhoan</a>}
                                                                          else
  {<a href="@Url.Action("ThongTinKhachHang","NguoiDung")"> @ViewBag.TenTaiKhoan</a> 
    <a href="@Url.Action("LichSuMuaHang","NguoiDung")"> Lịch sử mua hàng</a> }
} 

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/LichSuMuaHang.cshtml
@model List<WebSiteBanSach.Models.DonHang>
@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>Lịch sử mua hàng</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaDonHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayGiao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayDat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DaThanhToan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrangGiaoHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().KhachHang.HoTen)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDonHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaThanhToan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
            </td>
            @{if (item.TinhTrangGiaoHang == 0)
                {
                    <td>
                        @*Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaDonHang = item.MaDonHang }) |*@
                        @Html.ActionLink("Thanh toán", "ThanhToan", new { @MaDonHang = item.MaDonHang }) |
                    </td>
                }
            }
        </tr>
    }

</table>

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/ThongTinKhachHang.cshtml
@model WebSiteBanSach.Models.KhachHang

@{
    ViewBag.Title = "ThongTinKhachHang";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}


<h2>Chỉnh sửa thông tin khách hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Khách Hàng</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaKH</span>
                @Html.Hidden("MaKH", Model.MaKH)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen)
                @Html.ValidationMessageFor(model => model.HoTen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh)
                @Html.ValidationMessageFor(model => model.NgaySinh)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GioiTinh)
                @Html.ValidationMessageFor(model => model.GioiTinh)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai)
                @Html.ValidationMessageFor(model => model.DienThoai)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan)
                @Html.ValidationMessageFor(model => model.TaiKhoan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau)
                @Html.ValidationMessageFor(model => model.MatKhau)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>


    </div>
}

WebSiteBanSach/WebSiteBanSach/Views/NguoiDung/Xoa.cshtml
@model WebSiteBanSach.Models.DonHang

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}


<h3>Bạn có thật sự muốn xóa đơn hàng này?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaDonHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDonHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaThanhToan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaThanhToan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrangGiaoHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrangGiaoHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKH)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về", "LichSuMuaHang")
        </div>
    }
</div>